"""Correcciones en el modelo Programa

Revision ID: 60a839c990b8
Revises: 
Create Date: 2025-04-22 14:04:00.932576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a839c990b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programa_universitario', schema=None) as batch_op:
        batch_op.drop_index('ix_programa_universitario_codigo')

    op.drop_table('programa_universitario')
    with op.batch_alter_table('programa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asignatura_unidad_Curricular', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('area_curricular', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('eje_curricular', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('semestre', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('coordinador_asignatura_unidad', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('lapso_academico', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('prelacion', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('modalidad', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('docentes', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('unidad_credito', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('credito_academico', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ht', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('hp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('htp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('fecha_ultima_correcion', sa.Date(), nullable=False))
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_programa_codigo'), ['codigo'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programa_codigo'))
        batch_op.alter_column('codigo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('fecha_ultima_correcion')
        batch_op.drop_column('descripcion')
        batch_op.drop_column('htp')
        batch_op.drop_column('hp')
        batch_op.drop_column('ht')
        batch_op.drop_column('credito_academico')
        batch_op.drop_column('unidad_credito')
        batch_op.drop_column('docentes')
        batch_op.drop_column('modalidad')
        batch_op.drop_column('prelacion')
        batch_op.drop_column('lapso_academico')
        batch_op.drop_column('coordinador_asignatura_unidad')
        batch_op.drop_column('semestre')
        batch_op.drop_column('eje_curricular')
        batch_op.drop_column('area_curricular')
        batch_op.drop_column('asignatura_unidad_Curricular')

    op.create_table('programa_universitario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('asignatura_unidad_Curricular', sa.VARCHAR(length=100), nullable=False),
    sa.Column('area_curricular', sa.VARCHAR(length=100), nullable=False),
    sa.Column('eje_curricular', sa.VARCHAR(length=100), nullable=False),
    sa.Column('semestre', sa.INTEGER(), nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('coordinador_asignatura_unidad', sa.VARCHAR(length=100), nullable=False),
    sa.Column('lapso_academico', sa.VARCHAR(length=50), nullable=False),
    sa.Column('prelacion', sa.VARCHAR(length=50), nullable=False),
    sa.Column('modalidad', sa.VARCHAR(length=50), nullable=False),
    sa.Column('docentes', sa.VARCHAR(length=200), nullable=False),
    sa.Column('unidad_credito', sa.INTEGER(), nullable=False),
    sa.Column('credito_academico', sa.INTEGER(), nullable=False),
    sa.Column('ht', sa.INTEGER(), nullable=False),
    sa.Column('hp', sa.INTEGER(), nullable=False),
    sa.Column('htp', sa.INTEGER(), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=False),
    sa.Column('fecha_ultima_correcion', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('programa_universitario', schema=None) as batch_op:
        batch_op.create_index('ix_programa_universitario_codigo', ['codigo'], unique=1)

    # ### end Alembic commands ###
