"""Agregar columna archivo_word y hash_archivo

Revision ID: ae734e5da9df
Revises: 60a839c990b8
Create Date: 2025-04-29 22:05:26.450979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae734e5da9df'
down_revision = '60a839c990b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_word', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('hash_archivo', sa.String(length=64), nullable=True))
        batch_op.create_index('idx_busqueda', ['semestre', 'area_curricular', 'eje_curricular'], unique=False)
        batch_op.create_index(batch_op.f('ix_programa_area_curricular'), ['area_curricular'], unique=False)
        batch_op.create_index(batch_op.f('ix_programa_semestre'), ['semestre'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programa_semestre'))
        batch_op.drop_index(batch_op.f('ix_programa_area_curricular'))
        batch_op.drop_index('idx_busqueda')
        batch_op.drop_column('hash_archivo')
        batch_op.drop_column('archivo_word')

    # ### end Alembic commands ###
