"""Esquema inicial MySQL

Revision ID: 48ebbd037894
Revises: 
Create Date: 2026-03-01 13:43:11.973948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ebbd037894'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('programas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('asignatura_unidad_Curricular', sa.String(length=100), nullable=False),
    sa.Column('area_curricular', sa.String(length=100), nullable=False),
    sa.Column('eje_curricular', sa.String(length=100), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('coordinador_asignatura_unidad', sa.String(length=100), nullable=False),
    sa.Column('lapso_academico', sa.String(length=50), nullable=False),
    sa.Column('prelacion', sa.String(length=50), nullable=True),
    sa.Column('modalidad', sa.String(length=50), nullable=False),
    sa.Column('docentes', sa.String(length=200), nullable=False),
    sa.Column('unidad_credito', sa.Integer(), nullable=False),
    sa.Column('credito_academico', sa.Integer(), nullable=False),
    sa.Column('ht', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('htp', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_ultima_correcion', sa.Date(), nullable=True),
    sa.Column('archivo_word', sa.String(length=300), nullable=True),
    sa.Column('hash_archivo', sa.String(length=64), nullable=True),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('programas', schema=None) as batch_op:
        batch_op.create_index('idx_busqueda', ['semestre', 'area_curricular', 'eje_curricular'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programas', schema=None) as batch_op:
        batch_op.drop_index('idx_busqueda')

    op.drop_table('programas')
    op.drop_table('docentes')
    # ### end Alembic commands ###
