"""estructura absoluta del diagrama er ucla

Revision ID: abd39e43a43d
Revises: 
Create Date: 2026-06-21 19:47:31.836737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd39e43a43d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decanato_t',
    sa.Column('cod_dec', sa.String(length=50), nullable=False),
    sa.Column('nom_dec', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('cod_dec')
    )
    op.create_table('docente_t',
    sa.Column('cod_doc', sa.String(length=50), nullable=False),
    sa.Column('nom_doc', sa.String(length=100), nullable=True),
    sa.Column('ape_doc', sa.String(length=100), nullable=True),
    sa.Column('ced_doc', sa.String(length=20), nullable=True),
    sa.Column('tel_doc', sa.String(length=50), nullable=True),
    sa.Column('cor_doc', sa.String(length=100), nullable=True),
    sa.Column('fec_doc', sa.String(length=50), nullable=True),
    sa.Column('nac_doc', sa.String(length=50), nullable=True),
    sa.Column('sex_doc', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('cod_doc')
    )
    op.create_table('docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lapso_academico_t',
    sa.Column('cod_lap', sa.String(length=50), nullable=False),
    sa.Column('des_lap', sa.String(length=100), nullable=True),
    sa.Column('fec_ini', sa.Date(), nullable=True),
    sa.Column('fec_fin', sa.Date(), nullable=True),
    sa.Column('est_act', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('cod_lap')
    )
    op.create_table('materias_programas_t',
    sa.Column('cod_mat', sa.String(length=50), nullable=False),
    sa.Column('nom_mat', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('cod_mat')
    )
    op.create_table('usuario_t',
    sa.Column('cod_usu', sa.String(length=50), nullable=False),
    sa.Column('nom_usu', sa.String(length=100), nullable=True),
    sa.Column('cla_usu', sa.String(length=100), nullable=True),
    sa.Column('rol_usu', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('cod_usu')
    )
    op.create_table('carrera_t',
    sa.Column('cod_car', sa.String(length=50), nullable=False),
    sa.Column('nom_car', sa.String(length=150), nullable=True),
    sa.Column('cod_dec', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cod_dec'], ['decanato_t.cod_dec'], ),
    sa.PrimaryKeyConstraint('cod_car')
    )
    op.create_table('prelacion_m',
    sa.Column('cod_pre', sa.String(length=50), nullable=False),
    sa.Column('cod_mat', sa.String(length=50), nullable=True),
    sa.Column('cod_mat_pre', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cod_mat'], ['materias_programas_t.cod_mat'], ),
    sa.PrimaryKeyConstraint('cod_pre')
    )
    op.create_table('programas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('asignatura_unidad_Curricular', sa.String(length=150), nullable=False),
    sa.Column('area_curricular', sa.String(length=100), nullable=False),
    sa.Column('eje_curricular', sa.String(length=100), nullable=False),
    sa.Column('semestre', sa.String(length=20), nullable=False),
    sa.Column('coordinador_asignatura_unidad', sa.String(length=100), nullable=True),
    sa.Column('lapso_academico', sa.String(length=50), nullable=True),
    sa.Column('prelacion', sa.String(length=100), nullable=True),
    sa.Column('modalidad', sa.String(length=50), nullable=True),
    sa.Column('docentes', sa.Text(), nullable=True),
    sa.Column('unidad_credito', sa.Integer(), nullable=True),
    sa.Column('credito_academico', sa.Integer(), nullable=True),
    sa.Column('ht', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('htp', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_ultima_correcion', sa.Date(), nullable=True),
    sa.Column('estado_actual', sa.String(length=30), nullable=False),
    sa.Column('archivo_word', sa.String(length=300), nullable=True),
    sa.Column('hash_archivo', sa.String(length=64), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    with op.batch_alter_table('programas', schema=None) as batch_op:
        batch_op.create_index('idx_busqueda', ['semestre', 'area_curricular', 'eje_curricular'], unique=False)

    op.create_table('carrera_materia_m',
    sa.Column('cod_car_mat', sa.String(length=50), nullable=False),
    sa.Column('cod_car', sa.String(length=50), nullable=True),
    sa.Column('cod_mat', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cod_car'], ['carrera_t.cod_car'], ),
    sa.ForeignKeyConstraint(['cod_mat'], ['materias_programas_t.cod_mat'], ),
    sa.PrimaryKeyConstraint('cod_car_mat')
    )
    op.create_table('programa_versiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programa_id', sa.Integer(), nullable=False),
    sa.Column('version_numero', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo_real', sa.String(length=255), nullable=False),
    sa.Column('archivo_binario', sa.LargeBinary(length=16777215), nullable=False),
    sa.Column('enviado_por', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['programa_id'], ['programas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revision_programa_m',
    sa.Column('cod_pro', sa.String(length=50), nullable=False),
    sa.Column('cod_doc', sa.String(length=50), nullable=True),
    sa.Column('cod_car_mat', sa.String(length=50), nullable=True),
    sa.Column('fec_rev', sa.Date(), nullable=True),
    sa.Column('est_rev', sa.String(length=50), nullable=True),
    sa.Column('nom_arc', sa.String(length=255), nullable=True),
    sa.Column('obs_rev', sa.Text(), nullable=True),
    sa.Column('cod_lap', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cod_car_mat'], ['carrera_materia_m.cod_car_mat'], ),
    sa.ForeignKeyConstraint(['cod_doc'], ['docente_t.cod_doc'], ),
    sa.ForeignKeyConstraint(['cod_lap'], ['lapso_academico_t.cod_lap'], ),
    sa.PrimaryKeyConstraint('cod_pro')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revision_programa_m')
    op.drop_table('programa_versiones')
    op.drop_table('carrera_materia_m')
    with op.batch_alter_table('programas', schema=None) as batch_op:
        batch_op.drop_index('idx_busqueda')

    op.drop_table('programas')
    op.drop_table('prelacion_m')
    op.drop_table('carrera_t')
    op.drop_table('usuario_t')
    op.drop_table('materias_programas_t')
    op.drop_table('lapso_academico_t')
    op.drop_table('docentes')
    op.drop_table('docente_t')
    op.drop_table('decanato_t')
    # ### end Alembic commands ###
